"use client";
import { useState } from "react";
import Link from "next/link";
import { useAccount, useReadContract, useSignMessage, useSwitchChain } from "wagmi";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { AGLAR } from "@/lib/aglar";
import { complaintFields, complaintPayment, type ComplaintFields, type ComplaintRecord, type ComplaintAction } from "@/lib/complaints";
import { AgentRecordName } from "@/components/ComplaintRecords";
import { ComplaintInputs, sendComplaintAction } from "./Orders";
const ownerAbi=[{type:"function",name:"ownerOf",stateMutability:"view",inputs:[{name:"tokenId",type:"uint256"}],outputs:[{type:"address"}]}] as const;
export default function ComplaintDetail({id}:{id:string}) {
  const {address,chainId}=useAccount();const switching=useSwitchChain();const signer=useSignMessage();const cache=useQueryClient();
  const [eventPage,setEventPage]=useState(1);const [editing,setEditing]=useState(false);const [fields,setFields]=useState<ComplaintFields>({requested:"",happened:"",problem:"",evidence:""});const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const query=useQuery<{record:ComplaintRecord}>({queryKey:["complaints","detail",id,eventPage],queryFn:async()=>{const r=await fetch(`/api/complaints?id=${encodeURIComponent(id)}&eventPage=${eventPage}`);const data=await r.json();if(!r.ok)throw new Error(data.error);return data;},retry:false});
  const record=query.data?.record;
  const owner=useReadContract({address:record?AGLAR[record.chain].identity:undefined,abi:ownerAbi,functionName:"ownerOf",args:[BigInt(record?.agentId||0)],chainId:record?AGLAR[record.chain].chainId:undefined,query:{enabled:!!record&&!!address}});
  const isAuthor=!!address&&record?.author===address.toLowerCase();const isProvider=!!address&&owner.data?.toLowerCase()===address.toLowerCase();
  async function submit(action:ComplaintAction){setBusy(true);setError("");try{if(!record)throw new Error("Record unavailable.");const target=action.type==="reply"?AGLAR[record.chain].chainId:complaintPayment(record.initialDraft).chainId;if(chainId!==target)await switching.switchChainAsync({chainId:target});await sendComplaintAction(action,m=>signer.signMessageAsync({message:m,account:address}));setEditing(false);setMessage("");setEventPage(1);await cache.invalidateQueries({queryKey:["complaints"]});}catch(e){setError(e instanceof Error?e.message:"Update failed.");}finally{setBusy(false);}}
  return <main className="mx-auto max-w-4xl px-5 py-10"><Link className="text-sm underline" href="/orders">← Orders & complaint records</Link>
    {query.isPending&&<p className="mt-8" role="status">Loading record…</p>}{query.isError&&<p className="mt-8" role="alert">{query.error.message} <button className="underline" onClick={()=>query.refetch()}>Retry</button></p>}
    {record&&<><div className="mt-8 flex flex-wrap items-center gap-3 text-sm"><span className="rounded-full bg-[var(--yuzey)] px-4 py-2">{record.status==="resolved"?"Resolved by author":"Open complaint"}</span>{record.demo&&<span className="rounded-full bg-amber-50 px-4 py-2 text-amber-900">TEST · Demo record</span>}</div>
    <h1 className="mt-5 text-3xl"><AgentRecordName chain={record.chain} agentId={record.agentId}/></h1><p className="mt-2 text-sm text-[var(--soluk)]">{AGLAR[record.chain].ad} · #{record.agentId}</p><Link className="mt-3 inline-block text-sm underline" href={`/agent/${record.chain}/${record.agentId}`}>View agent →</Link>
    <div className="mt-6 rounded-xl bg-[var(--yuzey)] p-5 text-sm leading-6"><strong>Publication fee paid · 5 test USDC</strong><p className="mt-2">This verifies a payment to NOMEN for publication. Purchase, service use and the statements below are not independently verified. Responses and updates are free. This record is not a rating or a safety verdict.</p><a className="mt-3 inline-block underline" href={`${complaintPayment(record.initialDraft).explorer}/tx/${record.paymentTx}`} target="_blank" rel="noopener noreferrer">View {complaintPayment(record.initialDraft).name} payment ↗</a></div>
    {record.flags.length>0&&<div className="mt-5 rounded-xl border border-amber-300 p-4 text-sm text-amber-900">Automatic pattern flag: {record.flags.map(f=>f==="activity_spike"?"a burst of publications for this agent":"text repeated by another wallet").join("; ")}. This needs review and does not prove abuse.</div>}
    <p className="mt-5 break-all text-xs text-[var(--soluk)]">Author: {record.author} · Record {record.id} · Version {record.version}</p>
    <section className="mt-6 space-y-6 rounded-2xl border border-[var(--cizgi)] p-6">{(["requested","happened","problem","evidence"] as const).map(key=>[key,record.fields[key]] as const).map(([key,value])=><div key={key}><h2 className="font-medium">{key==="requested"?"What was requested":key==="happened"?"What happened":key==="problem"?"The reported problem":"Evidence reference · unverified"}</h2><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-7">{value||"No evidence reference supplied."}</p></div>)}</section>
    {!address&&<p className="mt-5 text-sm text-[var(--soluk)]">Connect the author wallet to update this record, or the agent owner wallet to respond.</p>}
    {isAuthor&&<section className="mt-6 rounded-xl border border-[var(--cizgi)] p-5"><h2 className="font-medium">Manage your record · no extra fee</h2><button className="dugme mt-4" disabled={busy} onClick={()=>{setFields(record.fields);setEditing(!editing);}}>Edit statement</button>{editing&&<div className="mt-5"><ComplaintInputs fields={fields} setFields={setFields} disabled={busy}/><button className="dugme mt-4" disabled={busy||!complaintFields.safeParse(fields).success} onClick={()=>submit({type:"edit",id,author:address!.toLowerCase(),version:record.version,timestamp:Date.now(),fields})}>Sign & save update</button></div>}
    <label className="mt-5 block text-sm">Resolution or reopening note<textarea className="girdi mt-2 min-h-24 w-full" value={message} onChange={e=>setMessage(e.target.value)} maxLength={1000} placeholder="Explain what was resolved, or why the issue remains open."/></label><button className="dugme mt-3" disabled={busy||message.trim().length<10} onClick={()=>submit({type:"status",id,author:address!.toLowerCase(),version:record.version,timestamp:Date.now(),status:record.status==="resolved"?"open":"resolved",message:message.trim()})}>{record.status==="resolved"?"Sign & reopen":"Sign & mark resolved"}</button></section>}
    {isProvider&&<section className="mt-6 rounded-xl border border-[var(--cizgi)] p-5"><h2 className="font-medium">Respond as the registered agent owner</h2><p className="mt-2 text-sm text-[var(--soluk)]">We recheck current registry ownership before accepting your signed response. Only the complaint author can mark the issue resolved.</p><textarea className="girdi mt-4 min-h-28 w-full" aria-label="Provider response" maxLength={2000} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Explain your position or offer a resolution (at least 20 characters)."/><button className="dugme mt-3" disabled={busy||message.trim().length<20} onClick={()=>submit({type:"reply",id,author:address!.toLowerCase(),version:record.version,timestamp:Date.now(),message:message.trim()})}>Sign & post response · free</button></section>}
    {busy&&<p className="mt-4" role="status">Confirm the action in your wallet…</p>}{error&&<p className="mt-4 break-words text-sm text-red-700" role="alert">{error}</p>}
    <section className="mt-8"><h2 className="text-xl font-medium">Record history</h2><p className="mt-2 text-sm text-[var(--soluk)]">Original statements and later signed updates remain visible. Provider ownership is checked at the time of each response.</p><div className="mt-5 space-y-4">{record.events?.map(e=><article className="rounded-xl border border-[var(--cizgi)] p-5" key={e.version}><h3 className="text-sm font-medium">{e.kind==="reply"?"Provider response":e.kind==="status"?"Author status update":e.kind==="edit"?"Author edited statement":e.kind==="publish"?"Publication fee verified":"Original signed draft"} · v{e.version}</h3><p className="mt-2 text-xs text-[var(--soluk)]">{e.actor.slice(0,6)}…{e.actor.slice(-4)} · {new Date(e.created_at).toLocaleString("en-US",{timeZone:"UTC"})} UTC</p>{(e.payload.type==="reply"||e.payload.type==="status")&&<p className="mt-3 whitespace-pre-wrap break-words text-sm">{e.payload.type==="status"&&<strong>{e.payload.status} · </strong>}{e.payload.message}</p>}<details className="mt-3 text-xs"><summary className="cursor-pointer">Signed record & evidence</summary><pre className="mt-3 max-h-80 overflow-auto whitespace-pre-wrap break-all">{JSON.stringify({payload:e.payload,signature:e.signature,ownerBlock:e.owner_block},null,2)}</pre></details></article>)}</div>
      <div className="mt-4 flex items-center gap-3"><button className="dugme" disabled={eventPage===1} onClick={()=>setEventPage(eventPage-1)}>Newer history</button><span className="text-xs">Page {eventPage}</span><button className="dugme" disabled={(record.events?.length||0)<20} onClick={()=>setEventPage(eventPage+1)}>Older history</button></div>
    </section></>}
  </main>;
}
