export default function Reproduce() {
  return <><h1>Reproduce a snapshot</h1>
    <p>The scanner processes an explicit id range. Ownership and URI reads use one pinned block; HTTP documents are fetched afterward and can change independently.</p>
    <pre><code>{`cd tarayici
./tazele.sh sepolia 10105
python3 -m unittest discover -s tests -v`}</code></pre>
    <p>The command writes a separate timestamped snapshot. Review unresolved ids, the manifest, metadata archives, rule dictionary and eligibility differences before publishing. It does not overwrite the website or submit a transaction.</p>
    <h2>Publication</h2><p>Assemble a release directory containing each chain’s final JSONL, Merkle proofs and manifest. Set NOMEN_SCAN_DIR to that directory, then run adim5_dizin.py and adim6_api_veri.py with all four chains. Publish the matching root only after reviewing the changes.</p>
    <h2>What can be verified</h2><p>Merkle leaves are keccak256(keccak256(abi.encode(agentId))); pairs are sorted before hashing. Proofs establish membership in the published eligible set. They do not establish metadata truth or agent safety. Reproducing classification additionally requires the exact archived documents, scanner version and dictionary.</p>
    <h2>September 11 test record addition</h2><p>Sepolia agent #10226 is a NOMEN-owned test record registered at block 11,679,005. Its embedded metadata was checked separately and added to the existing 1,420 passing records, giving 1,421 proofs. IDs between 10,105 and this new record remain unscanned; the older snapshot timestamp is preserved. The public <a href="/veri/sepolia/demo-evidence.json">addition evidence</a> records the transaction, metadata, checks and root transition. This addition is not a full rescan.</p><h2>Limits</h2><p>The September 9 Sepolia snapshot covers ids 1–10,105. Arbitrum Sepolia covers ids 1–205 at pinned block 307,933,498 and publishes 44 records that passed the current rules. Ethereum and non-listed Arc records retain legacy observations with unverified scan timestamps. The 249 listed Arc records were refreshed on September 11, 2026, at block 61,552,064. See /veri/arc/catalog-refresh.json for the limited scope. Public manifests distinguish these cases. HTTP fetches have a 20-second total process deadline, an 8-second socket timeout, bounded redirects and body size, and reject private-network destinations.</p>
  </>;
}
